name: Docker Build and Push

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap

        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          # If on the main branch, tag as latest and push
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository }}:latest -f ${{ github.workspace }}/Dockerfile.buildx ${{ github.workspace }} --push
        else
          # For other branches, tag with the branch name and push
          branch_name=$(basename "${{ github.ref }}")
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository }}:${branch_name} -f ${{ github.workspace }}/Dockerfile.buildx ${{ github.workspace }} --push
        fi

        docker buildx use default

    - name: Cleanup
      run: docker buildx stop

